# Generated by Django 3.1.2 on 2020-12-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1219', '0002_auto_20201219_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Longitude',
            new_name='votes',
        ),
    ]
